### ISSUE TITLE
Encoding OOPS on the monument

### ISSUE THREAD

**Issue by k5e** [chrismore/mozmonument2json#2]
There is a name on the monument that went wrong with encoding issues. 
![encoding-oops](https://f.cloud.github.com/assets/606885/2049252/cb97c97a-8a5c-11e3-8c59-cd9b68fc226b.png)

``` json
   {
      "side": "1",
      "panel": "lower",
      "row": "47",
      "number": "6",
      "name": "Arda Ã‡aÄŸlayaner"
   }
```

**Comment by chrismore** [comment]
I was worried it was an encoding issue with my json, but it looks like it it on the monument too. That means it is in the original Illustrator file that Barry used to design all of it.

**Comment by chrismore** [comment]
We need to get a main repo at /mozilla/monument/ where we can file bugs about the monument directly.

**Comment by chrismore** [comment]
@k5e can you file this issue here? https://github.com/mozilla/mozmonument-sf/issues

**Comment by k5e** [comment]
[X] done
